2025-07-02 17:45:58,160 - log_util.py[DEBUG]: Cloud-init v. 25.1.2-0ubuntu0~24.04.1 running 'init-local' at Wed, 02 Jul 2025 17:45:58 +0000. Up 6.22 seconds.
2025-07-02 17:45:58,160 - main.py[INFO]: PID [1] started cloud-init 'init-local'.
2025-07-02 17:45:58,160 - main.py[DEBUG]: No kernel command line url found.
2025-07-02 17:45:58,160 - main.py[DEBUG]: Closing stdin
2025-07-02 17:45:58,165 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-07-02 17:45:58,166 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-07-02 17:45:58,166 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2025-07-02 17:45:58,166 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2025-07-02 17:45:58,166 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2025-07-02 17:45:58,166 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-07-02 17:45:58,166 - stages.py[DEBUG]: no cache found
2025-07-02 17:45:58,166 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2025-07-02 17:45:58,169 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:45:58,169 - sources[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2025-07-02 17:45:58,191 - sources[DEBUG]: Searching for local data source in: ['DataSourceEc2Local']
2025-07-02 17:45:58,191 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2025-07-02 17:45:58,191 - sources[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2025-07-02 17:45:58,191 - sources[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-07-02 17:45:58,191 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-07-02 17:45:58,191 - util.py[DEBUG]: Reading 37 bytes from /sys/hypervisor/uuid
2025-07-02 17:45:58,191 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-07-02 17:45:58,191 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-07-02 17:45:58,191 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-07-02 17:45:58,191 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2025-07-02 17:45:58,192 - sources[DEBUG]: Detected DataSourceEc2Local
2025-07-02 17:45:58,192 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-07-02 17:45:58,192 - util.py[DEBUG]: Reading from /sys/class/net/enX0/name_assign_type (quiet=False)
2025-07-02 17:45:58,192 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/name_assign_type
2025-07-02 17:45:58,196 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/enX0/carrier (quiet=False)
2025-07-02 17:45:58,197 - net[DEBUG]: Interface has no carrier: enX0
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/enX0/dormant (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading from /sys/class/net/enX0/operstate (quiet=False)
2025-07-02 17:45:58,197 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/enX0/operstate
2025-07-02 17:45:58,197 - ephemeral.py[DEBUG]: No connectivity URLs provided. Skipping connectivity check before ephemeral network setup.
2025-07-02 17:45:58,197 - ephemeral.py[DEBUG]: No connectivity to IMDS, attempting DHCP setup.
2025-07-02 17:45:58,198 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,209 - performance.py[DEBUG]: Running ['ip', '--json', 'addr'] took 0.011 seconds
2025-07-02 17:45:58,209 - ephemeral.py[DEBUG]: No connectivity URLs provided. Skipping connectivity check before ephemeral network setup.
2025-07-02 17:45:58,209 - distros[DEBUG]: Using configured dhcp client priority list: ['dhcpcd', 'dhclient', 'udhcpc']
2025-07-02 17:45:58,209 - distros[DEBUG]: DHCP client selected: dhcpcd
2025-07-02 17:45:58,209 - dhcp.py[DEBUG]: Performing a dhcp discovery on enX0
2025-07-02 17:45:58,209 - subp.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'enX0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,213 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2025-07-02 17:45:58,213 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/type
2025-07-02 17:45:58,213 - subp.py[DEBUG]: Running command ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'enX0'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,708 - performance.py[DEBUG]: Running ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'enX0'] took 0.495 seconds
2025-07-02 17:45:58,708 - subp.py[DEBUG]: Running command ['dhcpcd', '--dumplease', '--ipv4only', 'enX0'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,712 - dhcp.py[DEBUG]: Parsing dhcpcd lease for interface enX0: 'reason=BOUND\ninterface=enX0\nprotocol=dhcp\nip_address=172.31.0.239\nsubnet_cidr=20\nnetwork_number=172.31.0.0\nsubnet_mask=255.255.240.0\nrouters=172.31.0.1\ndomain_name_servers=172.31.0.2\nhost_name=ip-172-31-0-239\ndomain_name=ap-south-1.compute.internal\ninterface_mtu=9001\nbroadcast_address=172.31.15.255\ndhcp_lease_time=3600\ndhcp_message_type=5\ndhcp_server_identifier=172.31.0.1\n'
2025-07-02 17:45:58,713 - util.py[DEBUG]: Reading from /var/lib/dhcpcd/enX0.lease (quiet=False)
2025-07-02 17:45:58,713 - util.py[DEBUG]: Reading 548 bytes from /var/lib/dhcpcd/enX0.lease
2025-07-02 17:45:58,713 - subp.py[DEBUG]: Running command ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'enX0', '-P'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,716 - util.py[DEBUG]: Reading from /run/dhcpcd/enX0-4.pid (quiet=False)
2025-07-02 17:45:58,716 - util.py[DEBUG]: Reading 4 bytes from /run/dhcpcd/enX0-4.pid
2025-07-02 17:45:58,716 - util.py[DEBUG]: Reading from /proc/447/stat (quiet=True)
2025-07-02 17:45:58,716 - util.py[DEBUG]: Reading 304 bytes from /proc/447/stat
2025-07-02 17:45:58,716 - dhcp.py[DEBUG]: killing dhcpcd with pid=447 gid=446
2025-07-02 17:45:58,717 - ephemeral.py[DEBUG]: Received dhcp lease on enX0 for 172.31.0.239/255.255.240.0
2025-07-02 17:45:58,717 - ephemeral.py[DEBUG]: Attempting setup of ephemeral network on enX0 with 172.31.0.239/20 brd 172.31.15.255
2025-07-02 17:45:58,717 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,719 - ephemeral.py[DEBUG]: Skip adding ip address: enX0 already has address 172.31.0.239
2025-07-02 17:45:58,719 - ephemeral.py[DEBUG]: Skip bringing up network link: interface enX0 is already up
2025-07-02 17:45:58,719 - subp.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,721 - ephemeral.py[DEBUG]: Skip ephemeral route setup. enX0 already has default route: default via 172.31.0.1 dev enX0 proto dhcp src 172.31.0.239 metric 1002 mtu 9001
2025-07-02 17:45:58,721 - ephemeral.py[DEBUG]: Successfully brought up enX0 for ephemeral ipv4 networking.
2025-07-02 17:45:58,721 - util.py[DEBUG]: Reading from /sys/class/net/enX0/operstate (quiet=False)
2025-07-02 17:45:58,721 - util.py[DEBUG]: Reading 3 bytes from /sys/class/net/enX0/operstate
2025-07-02 17:45:58,721 - ephemeral.py[DEBUG]: Successfully brought up enX0 for ephemeral ipv6 networking.
2025-07-02 17:45:58,725 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2025-07-02 17:45:58,725 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-07-02 17:45:58,726 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'stream': False, 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,750 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
2025-07-02 17:45:58,750 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2025-07-02 17:45:58,750 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,752 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-07-02 17:45:58,752 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-07-02 17:45:58,753 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/user-data' with {'url': 'http://169.254.169.254/2021-03-23/user-data', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,754 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/user-data (200, 950b) after 1 attempts
2025-07-02 17:45:58,754 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,756 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ (200, 326b) after 1 attempts
2025-07-02 17:45:58,756 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,758 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ (200, 30b) after 1 attempts
2025-07-02 17:45:58,758 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,759 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-07-02 17:45:58,759 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,761 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0 (200, 3b) after 1 attempts
2025-07-02 17:45:58,761 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,762 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1 (200, 3b) after 1 attempts
2025-07-02 17:45:58,763 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,764 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-07-02 17:45:58,764 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,766 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-07-02 17:45:58,766 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,768 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-07-02 17:45:58,768 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,769 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-07-02 17:45:58,770 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,771 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-07-02 17:45:58,771 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/hibernation/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/hibernation/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,772 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/hibernation/ (200, 10b) after 1 attempts
2025-07-02 17:45:58,773 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/hibernation/configured' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/hibernation/configured', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,774 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/hibernation/configured (200, 5b) after 1 attempts
2025-07-02 17:45:58,774 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,776 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-07-02 17:45:58,776 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,777 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-07-02 17:45:58,777 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,779 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-07-02 17:45:58,780 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/metrics/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,782 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-07-02 17:45:58,782 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,783 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-07-02 17:45:58,784 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,785 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-07-02 17:45:58,786 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,787 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-07-02 17:45:58,787 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,789 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-07-02 17:45:58,789 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,791 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ (200, 230b) after 1 attempts
2025-07-02 17:45:58,791 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,798 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/ (200, 11b) after 1 attempts
2025-07-02 17:45:58,798 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/3.110.43.75' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/3.110.43.75', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,800 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/ipv4-associations/3.110.43.75 (200, 12b) after 1 attempts
2025-07-02 17:45:58,800 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/device-number' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/device-number', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,802 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/device-number (200, 1b) after 1 attempts
2025-07-02 17:45:58,802 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/interface-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/interface-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,803 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/interface-id (200, 21b) after 1 attempts
2025-07-02 17:45:58,804 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,805 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-hostname (200, 43b) after 1 attempts
2025-07-02 17:45:58,805 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-ipv4s' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-ipv4s', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,808 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/local-ipv4s (200, 12b) after 1 attempts
2025-07-02 17:45:58,808 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/mac' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/mac', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,810 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/mac (200, 17b) after 1 attempts
2025-07-02 17:45:58,810 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/owner-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/owner-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,811 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/owner-id (200, 12b) after 1 attempts
2025-07-02 17:45:58,811 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,813 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-hostname (200, 48b) after 1 attempts
2025-07-02 17:45:58,813 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-ipv4s' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-ipv4s', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,814 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/public-ipv4s (200, 11b) after 1 attempts
2025-07-02 17:45:58,814 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-group-ids' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-group-ids', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,817 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-group-ids (200, 20b) after 1 attempts
2025-07-02 17:45:58,818 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-groups' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-groups', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,819 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/security-groups (200, 10b) after 1 attempts
2025-07-02 17:45:58,819 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,821 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-id (200, 24b) after 1 attempts
2025-07-02 17:45:58,821 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-ipv4-cidr-block', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,823 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2025-07-02 17:45:58,823 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,824 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-id (200, 21b) after 1 attempts
2025-07-02 17:45:58,825 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-block', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,826 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-07-02 17:45:58,826 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-blocks', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,828 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/0a:07:11:86:44:c3/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-07-02 17:45:58,828 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,830 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-07-02 17:45:58,830 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,832 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone (200, 11b) after 1 attempts
2025-07-02 17:45:58,832 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,834 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-07-02 17:45:58,834 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/region', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,835 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/region (200, 10b) after 1 attempts
2025-07-02 17:45:58,836 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-keys/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,837 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-keys/ (200, 13b) after 1 attempts
2025-07-02 17:45:58,838 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-keys/0/openssh-key', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,839 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-keys/0/openssh-key (200, 93b) after 1 attempts
2025-07-02 17:45:58,839 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,841 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-07-02 17:45:58,841 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/domain', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,842 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-07-02 17:45:58,843 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/partition', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,844 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-07-02 17:45:58,844 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,846 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-07-02 17:45:58,846 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-launch-index', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,852 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-07-02 17:45:58,852 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,854 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-07-02 17:45:58,854 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,856 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/hostname (200, 43b) after 1 attempts
2025-07-02 17:45:58,857 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-action', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,858 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-07-02 17:45:58,858 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,861 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-07-02 17:45:58,861 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,863 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-07-02 17:45:58,864 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-type', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,865 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-07-02 17:45:58,866 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/local-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,867 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/local-hostname (200, 43b) after 1 attempts
2025-07-02 17:45:58,867 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/local-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,869 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2025-07-02 17:45:58,869 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/mac', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,871 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-07-02 17:45:58,871 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/profile', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,873 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-07-02 17:45:58,873 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,876 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-hostname (200, 48b) after 1 attempts
2025-07-02 17:45:58,876 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,877 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-ipv4 (200, 11b) after 1 attempts
2025-07-02 17:45:58,878 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/reservation-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,879 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-07-02 17:45:58,880 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/security-groups', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,881 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/security-groups (200, 10b) after 1 attempts
2025-07-02 17:45:58,882 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,884 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-07-02 17:45:58,884 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/document', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,885 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/document (200, 478b) after 1 attempts
2025-07-02 17:45:58,885 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,887 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1175b) after 1 attempts
2025-07-02 17:45:58,887 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,888 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1495b) after 1 attempts
2025-07-02 17:45:58,889 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.2-0ubuntu0~24.04.1'}} configuration
2025-07-02 17:45:58,890 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-07-02 17:45:58,890 - DataSourceEc2.py[DEBUG]: Crawled metadata service using link-local ipv6
2025-07-02 17:45:58,890 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'enX0', 'down'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,892 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '172.31.0.239/20', 'dev', 'enX0'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,895 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-07-02 17:45:58,896 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-07-02 17:45:58,896 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp1e822ioq) - w: [600] 14410 bytes/chars
2025-07-02 17:45:58,897 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpttxtdrje) - w: [644] 7855 bytes/chars
2025-07-02 17:45:58,897 - performance.py[DEBUG]: Getting metadata took 0.706 seconds
2025-07-02 17:45:58,897 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2025-07-02 17:45:58,898 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-07-02 17:45:58,898 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2025-07-02 17:45:58,898 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-02 17:45:58,898 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-07-02 17:45:58,898 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,905 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-07-02 17:45:58,905 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-07-02 17:45:58,905 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,906 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-07-02 17:45:58,906 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-07-02 17:45:58,906 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,906 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-02 17:45:58,906 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-02 17:45:58,906 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,908 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-02 17:45:58,908 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-07-02 17:45:58,908 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,908 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,908 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:45:58,909 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-07-02 17:45:58,909 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0dea03404379d6b00'
2025-07-02 17:45:58,910 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0dea03404379d6b00/datasource (quiet=False)
2025-07-02 17:45:58,910 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/datasource - wb: [644] 39 bytes
2025-07-02 17:45:58,910 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2025-07-02 17:45:58,911 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-07-02 17:45:58,911 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-07-02 17:45:58,911 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-07-02 17:45:58,911 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-07-02 17:45:58,911 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-07-02 17:45:58,912 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 13078 bytes
2025-07-02 17:45:58,912 - main.py[DEBUG]: [local] init will now be targeting instance id: i-0dea03404379d6b00. new=True
2025-07-02 17:45:58,912 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-02 17:45:58,912 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-07-02 17:45:58,912 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,918 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-07-02 17:45:58,918 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-07-02 17:45:58,918 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,919 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-07-02 17:45:58,919 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-07-02 17:45:58,919 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,919 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-02 17:45:58,919 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-02 17:45:58,919 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,922 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-02 17:45:58,922 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-07-02 17:45:58,922 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,923 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:45:58,923 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:45:58,923 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:45:58,924 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-0-239.ap-south-1.compute.internal (ip-172-31-0-239)
2025-07-02 17:45:58,924 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2025-07-02 17:45:58,924 - util.py[DEBUG]: Reading 7 bytes from /etc/hostname
2025-07-02 17:45:58,924 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 16 bytes
2025-07-02 17:45:58,924 - distros[DEBUG]: Non-persistently setting the system hostname to ip-172-31-0-239
2025-07-02 17:45:58,924 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-0-239'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,926 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpy1o7rqg7) - w: [644] 91 bytes/chars
2025-07-02 17:45:58,927 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,927 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/name_assign_type (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/name_assign_type
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/carrier (quiet=False)
2025-07-02 17:45:58,928 - net[DEBUG]: Interface has no carrier: enX0
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/dormant (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/operstate (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/enX0/operstate
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/addr_assign_type
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/enX0/uevent
2025-07-02 17:45:58,928 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,929 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/type
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-07-02 17:45:58,929 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-07-02 17:45:58,931 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-07-02 17:45:58,931 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,931 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,931 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,931 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,931 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/instance/network-config.json (via temporary file /var/lib/cloud/instance/tmph77s5dke) - w: [600] 171 bytes/chars
2025-07-02 17:45:58,931 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/network-config.json' => '/var/lib/cloud/instance/network-config.json'
2025-07-02 17:45:58,932 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-07-02 17:45:58,933 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-07-02 17:45:58,933 - schema.py[DEBUG]: Validating network-config with netplan API
2025-07-02 17:45:58,934 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmp3g4jh63s/etc/netplan/network-config.yaml - wb: [600] 202 bytes
2025-07-02 17:45:58,935 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,935 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/addr_assign_type
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/enX0/uevent
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/type
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-07-02 17:45:58,936 - networking.py[DEBUG]: net: all expected physical devices present
2025-07-02 17:45:58,936 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'enX0': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '0a:07:11:86:44:c3'}, 'set-name': 'enX0'}}}
2025-07-02 17:45:58,936 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/addr_assign_type
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/enX0/uevent
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/enX0/operstate (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/enX0/operstate
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2025-07-02 17:45:58,937 - util.py[DEBUG]: Reading 8 bytes from /sys/class/net/lo/operstate
2025-07-02 17:45:58,938 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,940 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:58,941 - net[DEBUG]: Detected interfaces {'enX0': {'downable': True, 'device_id': None, 'driver': 'vif', 'mac': '0a:07:11:86:44:c3', 'name': 'enX0', 'up': False}, 'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}}
2025-07-02 17:45:58,941 - net[DEBUG]: no work necessary for renaming of [['0a:07:11:86:44:c3', 'enX0', 'vif', None]]
2025-07-02 17:45:58,941 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 2, 'ethernets': {'enX0': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '0a:07:11:86:44:c3'}, 'set-name': 'enX0'}}}
2025-07-02 17:45:58,942 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 23 bytes
2025-07-02 17:45:58,942 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-07-02 17:45:58,942 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-07-02 17:45:58,943 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-07-02 17:45:58,944 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-07-02 17:45:58,944 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:59,492 - performance.py[DEBUG]: Running ['netplan', 'generate'] took 0.548 seconds
2025-07-02 17:45:59,492 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/enX0'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:59,497 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:45:59,500 - distros[DEBUG]: Not bringing up newly configured network interfaces
2025-07-02 17:45:59,500 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2025-07-02 17:45:59,500 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-02 17:45:59,500 - util.py[DEBUG]: Reading 10 bytes from /proc/uptime
2025-07-02 17:45:59,501 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpydco2wh0) - w: [644] 499 bytes/chars
2025-07-02 17:45:59,501 - performance.py[DEBUG]: cloud-init stage: 'init-local' took 1.380 seconds
2025-07-02 17:45:59,501 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2025-07-02 17:46:01,267 - log_util.py[DEBUG]: Cloud-init v. 25.1.2-0ubuntu0~24.04.1 running 'init' at Wed, 02 Jul 2025 17:46:01 +0000. Up 9.33 seconds.
2025-07-02 17:46:01,267 - main.py[INFO]: PID [1] started cloud-init 'init'.
2025-07-02 17:46:01,267 - main.py[DEBUG]: No kernel command line url found.
2025-07-02 17:46:01,267 - main.py[DEBUG]: Closing stdin
2025-07-02 17:46:01,271 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-07-02 17:46:01,271 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-07-02 17:46:01,271 - util.py[DEBUG]: Reading from /var/lib/cloud/data/python-version (quiet=False)
2025-07-02 17:46:01,271 - util.py[DEBUG]: Reading 4 bytes from /var/lib/cloud/data/python-version
2025-07-02 17:46:01,272 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,275 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,276 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-07-02 17:46:01,319 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-07-02 17:46:01,319 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-07-02 17:46:01,319 - util.py[DEBUG]: Reading 13078 bytes from /var/lib/cloud/instance/obj.pkl
2025-07-02 17:46:01,322 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2025-07-02 17:46:01,322 - util.py[DEBUG]: Reading 20 bytes from /run/cloud-init/.instance-id
2025-07-02 17:46:01,322 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2025-07-02 17:46:01,322 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2025-07-02 17:46:01,322 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-02 17:46:01,322 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-07-02 17:46:01,322 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,327 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-07-02 17:46:01,327 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-07-02 17:46:01,327 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,328 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-07-02 17:46:01,328 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-07-02 17:46:01,328 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,328 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-02 17:46:01,328 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-02 17:46:01,329 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,330 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-02 17:46:01,330 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-07-02 17:46:01,330 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,330 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,330 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:46:01,331 - stages.py[INFO]: Instance link already exists, not recreating it.
2025-07-02 17:46:01,331 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0dea03404379d6b00/datasource (quiet=False)
2025-07-02 17:46:01,331 - util.py[DEBUG]: Reading 39 bytes from /var/lib/cloud/instances/i-0dea03404379d6b00/datasource
2025-07-02 17:46:01,331 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/datasource - wb: [644] 39 bytes
2025-07-02 17:46:01,331 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2025-07-02 17:46:01,332 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-07-02 17:46:01,332 - util.py[DEBUG]: Reading 20 bytes from /var/lib/cloud/data/instance-id
2025-07-02 17:46:01,332 - stages.py[DEBUG]: previous iid found to be i-0dea03404379d6b00
2025-07-02 17:46:01,332 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-07-02 17:46:01,332 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-07-02 17:46:01,332 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2025-07-02 17:46:01,333 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 13267 bytes
2025-07-02 17:46:01,333 - stages.py[INFO]: Not re-loading configuration, instance id and datasource have not changed.
2025-07-02 17:46:01,333 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0dea03404379d6b00. new=False
2025-07-02 17:46:01,333 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/addr_assign_type
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/enX0/uevent
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:46:01,334 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-07-02 17:46:01,334 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/type
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-07-02 17:46:01,335 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-07-02 17:46:01,335 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2025-07-02 17:46:01,335 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2025-07-02 17:46:01,335 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>, <EventType.HOTPLUG: 'hotplug'>}}
2025-07-02 17:46:01,335 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2025-07-02 17:46:01,335 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2025-07-02 17:46:01,335 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'enX0': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '0a:07:11:86:44:c3'}, 'set-name': 'enX0'}}}
2025-07-02 17:46:01,335 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enX0/addr_assign_type
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/enX0/uevent
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enX0/address
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/enX0/operstate (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 3 bytes from /sys/class/net/enX0/operstate
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2025-07-02 17:46:01,336 - util.py[DEBUG]: Reading 8 bytes from /sys/class/net/lo/operstate
2025-07-02 17:46:01,337 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,338 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,339 - net[DEBUG]: Detected interfaces {'enX0': {'downable': False, 'device_id': None, 'driver': 'vif', 'mac': '0a:07:11:86:44:c3', 'name': 'enX0', 'up': True}, 'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}}
2025-07-02 17:46:01,339 - net[DEBUG]: no work necessary for renaming of [['0a:07:11:86:44:c3', 'enX0', 'vif', None]]
2025-07-02 17:46:01,339 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-07-02 17:46:01,339 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-07-02 17:46:01,340 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/user-data.txt - wb: [600] 950 bytes
2025-07-02 17:46:01,342 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/user-data.txt.i - wb: [600] 1256 bytes
2025-07-02 17:46:01,342 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/vendor-data.txt - wb: [600] 0 bytes
2025-07-02 17:46:01,343 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/vendor-data.txt.i - wb: [600] 308 bytes
2025-07-02 17:46:01,343 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/vendor-data2.txt - wb: [600] 0 bytes
2025-07-02 17:46:01,344 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/vendor-data2.txt.i - wb: [600] 308 bytes
2025-07-02 17:46:01,344 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-07-02 17:46:01,344 - util.py[DEBUG]: Reading 91 bytes from /var/lib/cloud/data/set-hostname
2025-07-02 17:46:01,344 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set_hostname
2025-07-02 17:46:01,344 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/consume_data - wb: [644] 24 bytes
2025-07-02 17:46:01,345 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/consume_data'>)
2025-07-02 17:46:01,345 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-07-02 17:46:01,345 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-07-02 17:46:01,345 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,345 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/x-shellscript', 'Content-Disposition': 'attachment; filename="part-001"'}
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, part-001, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/part-001 - wb: [700] 950 bytes
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-07-02 17:46:01,346 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/cloud-config.txt - wb: [600] 0 bytes
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-07-02 17:46:01,346 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-07-02 17:46:01,346 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-07-02 17:46:01,346 - stages.py[DEBUG]: no vendordata from datasource
2025-07-02 17:46:01,346 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-07-02 17:46:01,347 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-07-02 17:46:01,347 - stages.py[DEBUG]: no vendordata2 from datasource
2025-07-02 17:46:01,347 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-07-02 17:46:01,347 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-02 17:46:01,347 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-07-02 17:46:01,347 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,352 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-07-02 17:46:01,352 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-07-02 17:46:01,352 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,353 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-07-02 17:46:01,353 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-07-02 17:46:01,353 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,353 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-02 17:46:01,353 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-02 17:46:01,353 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,355 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-02 17:46:01,355 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-07-02 17:46:01,355 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,356 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,356 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:46:01,356 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-07-02 17:46:01,356 - util.py[DEBUG]: Reading 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-07-02 17:46:01,356 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,356 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:46:01,357 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/combined-cloud-config.json (via temporary file /run/cloud-init/tmpwydmm30b) - w: [600] 5609 bytes/chars
2025-07-02 17:46:01,357 - util.py[DEBUG]: Reading from /run/cloud-init/instance-data-sensitive.json (quiet=False)
2025-07-02 17:46:01,357 - util.py[DEBUG]: Reading 14410 bytes from /run/cloud-init/instance-data-sensitive.json
2025-07-02 17:46:01,357 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp001edbqh) - w: [600] 16641 bytes/chars
2025-07-02 17:46:01,357 - main.py[DEBUG]: Skipping user-data validation. No user-data found.
2025-07-02 17:46:01,358 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-07-02 17:46:01,358 - util.py[DEBUG]: Reading 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-07-02 17:46:01,358 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-02 17:46:01,358 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-02 17:46:01,359 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-07-02 17:46:01,359 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16639 bytes
2025-07-02 17:46:01,360 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-07-02 17:46:01,360 - main.py[DEBUG]: no di_report found in config.
2025-07-02 17:46:01,376 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:46:01,377 - modules.py[INFO]: Skipping modules 'bootcmd,write_files,disk_setup,update_etc_hosts,ca_certs,rsyslog' because no applicable config is provided.
2025-07-02 17:46:01,377 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-07-02 17:46:01,377 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-07-02 17:46:01,377 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_seed_random - wb: [644] 23 bytes
2025-07-02 17:46:01,378 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_seed_random'>)
2025-07-02 17:46:01,378 - cc_seed_random.py[DEBUG]: no command provided
2025-07-02 17:46:01,378 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully and took 0.000 seconds
2025-07-02 17:46:01,378 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-07-02 17:46:01,378 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-07-02 17:46:01,378 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x74d0497ca060>)
2025-07-02 17:46:01,378 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-07-02 17:46:01,378 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,381 - util.py[DEBUG]: Reading from /proc/519/mountinfo (quiet=False)
2025-07-02 17:46:01,381 - util.py[DEBUG]: Reading 2555 bytes from /proc/519/mountinfo
2025-07-02 17:46:01,382 - cc_growpart.py[DEBUG]: growpart found fs=ext4
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading 2 bytes from /sys/class/block/xvda1/partition
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading from /sys/devices/vbd-768/block/xvda/dev (quiet=False)
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading 6 bytes from /sys/devices/vbd-768/block/xvda/dev
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading from /proc/519/mountinfo (quiet=False)
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading 2555 bytes from /proc/519/mountinfo
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading from /proc/519/mountinfo (quiet=False)
2025-07-02 17:46:01,382 - util.py[DEBUG]: Reading 2555 bytes from /proc/519/mountinfo
2025-07-02 17:46:01,382 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,427 - performance.py[DEBUG]: Running ['growpart', '--dry-run', '/dev/xvda', '1'] took 0.044 seconds
2025-07-02 17:46:01,427 - performance.py[DEBUG]: Resizing devices took 0.046 seconds
2025-07-02 17:46:01,427 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
2025-07-02 17:46:01,427 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully and took 0.049 seconds
2025-07-02 17:46:01,427 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-07-02 17:46:01,427 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-07-02 17:46:01,428 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x74d0497ca060>)
2025-07-02 17:46:01,428 - util.py[DEBUG]: Reading from /proc/519/mountinfo (quiet=False)
2025-07-02 17:46:01,428 - util.py[DEBUG]: Reading 2555 bytes from /proc/519/mountinfo
2025-07-02 17:46:01,428 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/root mnt_point=/ path=/
2025-07-02 17:46:01,428 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/root
2025-07-02 17:46:01,428 - subp.py[DEBUG]: Running command ('resize2fs', '/dev/root') with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,435 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2025-07-02 17:46:01,435 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully and took 0.008 seconds
2025-07-02 17:46:01,436 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-07-02 17:46:01,436 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-07-02 17:46:01,436 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_mounts - wb: [644] 23 bytes
2025-07-02 17:46:01,436 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_mounts'>)
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-07-02 17:46:01,436 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-07-02 17:46:01,436 - util.py[DEBUG]: Reading 146 bytes from /etc/fstab
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: changed ephemeral0 => None
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-07-02 17:46:01,436 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-07-02 17:46:01,436 - cc_mounts.py[DEBUG]: changed swap => None
2025-07-02 17:46:01,437 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-07-02 17:46:01,437 - cc_mounts.py[DEBUG]: no need to setup swap
2025-07-02 17:46:01,437 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-07-02 17:46:01,437 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully and took 0.001 seconds
2025-07-02 17:46:01,437 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2025-07-02 17:46:01,437 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2025-07-02 17:46:01,437 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_set_hostname - wb: [644] 24 bytes
2025-07-02 17:46:01,437 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_set_hostname'>)
2025-07-02 17:46:01,437 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-07-02 17:46:01,437 - util.py[DEBUG]: Reading 91 bytes from /var/lib/cloud/data/set-hostname
2025-07-02 17:46:01,437 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set_hostname
2025-07-02 17:46:01,437 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully and took 0.001 seconds
2025-07-02 17:46:01,437 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-07-02 17:46:01,437 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-07-02 17:46:01,438 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x74d0497c9370>)
2025-07-02 17:46:01,438 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-0-239.ap-south-1.compute.internal (ip-172-31-0-239)
2025-07-02 17:46:01,438 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2025-07-02 17:46:01,438 - util.py[DEBUG]: Reading 16 bytes from /etc/hostname
2025-07-02 17:46:01,438 - distros[DEBUG]: Attempting to update hostname to ip-172-31-0-239 in 1 files
2025-07-02 17:46:01,438 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2025-07-02 17:46:01,438 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 16 bytes
2025-07-02 17:46:01,438 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully and took 0.001 seconds
2025-07-02 17:46:01,438 - modules.py[DEBUG]: Running module users_groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-07-02 17:46:01,438 - handlers.py[DEBUG]: start: init-network/config-users_groups: running config-users_groups with frequency once-per-instance
2025-07-02 17:46:01,438 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_users_groups - wb: [644] 24 bytes
2025-07-02 17:46:01,439 - helpers.py[DEBUG]: Running config-users_groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_users_groups'>)
2025-07-02 17:46:01,439 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-07-02 17:46:01,439 - util.py[DEBUG]: Reading 400 bytes from /etc/os-release
2025-07-02 17:46:01,440 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-07-02 17:46:01,440 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-07-02 17:46:01,440 - distros[DEBUG]: Adding user ubuntu
2025-07-02 17:46:01,440 - subp.py[DEBUG]: Running command ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,cdrom,dip,lxd,sudo', '--shell', '/bin/bash', '-m'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,486 - performance.py[DEBUG]: Running ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,cdrom,dip,lxd,sudo', '--shell', '/bin/bash', '-m'] took 0.046 seconds
2025-07-02 17:46:01,486 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:01,497 - performance.py[DEBUG]: Running ['passwd', '-l', 'ubuntu'] took 0.010 seconds
2025-07-02 17:46:01,497 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-07-02 17:46:01,497 - util.py[DEBUG]: Reading 1800 bytes from /etc/sudoers
2025-07-02 17:46:01,499 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 141 bytes
2025-07-02 17:46:01,499 - handlers.py[DEBUG]: finish: init-network/config-users_groups: SUCCESS: config-users_groups ran successfully and took 0.061 seconds
2025-07-02 17:46:01,499 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-07-02 17:46:01,499 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-07-02 17:46:01,499 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_ssh - wb: [644] 23 bytes
2025-07-02 17:46:01,500 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_ssh'>)
2025-07-02 17:46:01,500 - util.py[DEBUG]: Reading from /proc/sys/crypto/fips_enabled (quiet=False)
2025-07-02 17:46:01,500 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:03,549 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] took 2.049 seconds
2025-07-02 17:46:03,550 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:03,556 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading 102 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading 574 bytes from /etc/ssh/ssh_host_rsa_key.pub
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-07-02 17:46:03,562 - util.py[DEBUG]: Reading 182 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-07-02 17:46:03,563 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-07-02 17:46:03,563 - util.py[DEBUG]: Reading 3517 bytes from /etc/ssh/sshd_config
2025-07-02 17:46:03,563 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2025-07-02 17:46:03,563 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-02 17:46:03,563 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2025-07-02 17:46:03,563 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2025-07-02 17:46:03,564 - util.py[DEBUG]: Reading 0 bytes from /home/ubuntu/.ssh/authorized_keys
2025-07-02 17:46:03,564 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 93 bytes
2025-07-02 17:46:03,564 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-07-02 17:46:03,564 - util.py[DEBUG]: Reading 3517 bytes from /etc/ssh/sshd_config
2025-07-02 17:46:03,565 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-02 17:46:03,565 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-07-02 17:46:03,565 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-07-02 17:46:03,565 - util.py[DEBUG]: Reading 0 bytes from /root/.ssh/authorized_keys
2025-07-02 17:46:03,565 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 257 bytes
2025-07-02 17:46:03,565 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully and took 2.066 seconds
2025-07-02 17:46:03,565 - modules.py[DEBUG]: Running module set_passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-07-02 17:46:03,566 - handlers.py[DEBUG]: start: init-network/config-set_passwords: running config-set_passwords with frequency once-per-instance
2025-07-02 17:46:03,566 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_set_passwords - wb: [644] 24 bytes
2025-07-02 17:46:03,566 - helpers.py[DEBUG]: Running config-set_passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_set_passwords'>)
2025-07-02 17:46:03,566 - cc_set_passwords.py[DEBUG]: Leaving SSH config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2025-07-02 17:46:03,566 - handlers.py[DEBUG]: finish: init-network/config-set_passwords: SUCCESS: config-set_passwords ran successfully and took 0.000 seconds
2025-07-02 17:46:03,566 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-07-02 17:46:03,566 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-02 17:46:03,566 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-07-02 17:46:03,566 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp9x8b9daj) - w: [644] 500 bytes/chars
2025-07-02 17:46:03,567 - performance.py[DEBUG]: cloud-init stage: 'init-network' took 2.337 seconds
2025-07-02 17:46:03,567 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-07-02 17:46:05,927 - log_util.py[DEBUG]: Cloud-init v. 25.1.2-0ubuntu0~24.04.1 running 'modules:config' at Wed, 02 Jul 2025 17:46:05 +0000. Up 13.93 seconds.
2025-07-02 17:46:05,927 - main.py[INFO]: PID [1] started cloud-init 'modules:config'.
2025-07-02 17:46:05,997 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:46:06,001 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt_pipelining,ubuntu_pro,ntp,timezone,disable_ec2_metadata,runcmd' because no applicable config is provided.
2025-07-02 17:46:06,001 - modules.py[DEBUG]: Running module ssh_import_id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2025-07-02 17:46:06,001 - handlers.py[DEBUG]: start: modules-config/config-ssh_import_id: running config-ssh_import_id with frequency once-per-instance
2025-07-02 17:46:06,001 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_ssh_import_id - wb: [644] 23 bytes
2025-07-02 17:46:06,002 - helpers.py[DEBUG]: Running config-ssh_import_id using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_ssh_import_id'>)
2025-07-02 17:46:06,002 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh_import_id, no 'ssh_import_id' directives found.
2025-07-02 17:46:06,002 - handlers.py[DEBUG]: finish: modules-config/config-ssh_import_id: SUCCESS: config-ssh_import_id ran successfully and took 0.000 seconds
2025-07-02 17:46:06,002 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-07-02 17:46:06,002 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-07-02 17:46:06,002 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_locale - wb: [644] 24 bytes
2025-07-02 17:46:06,002 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_locale'>)
2025-07-02 17:46:06,002 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2025-07-02 17:46:06,002 - util.py[DEBUG]: Reading 13 bytes from /etc/default/locale
2025-07-02 17:46:06,002 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8
2025-07-02 17:46:06,002 - debian.py[DEBUG]: System locale set to C.UTF-8 via /etc/default/locale
2025-07-02 17:46:06,003 - debian.py[DEBUG]: System has 'LANG=C.UTF-8' requested 'C.UTF-8', skipping regeneration.
2025-07-02 17:46:06,003 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully and took 0.001 seconds
2025-07-02 17:46:06,003 - modules.py[DEBUG]: Running module grub_dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2025-07-02 17:46:06,003 - handlers.py[DEBUG]: start: modules-config/config-grub_dpkg: running config-grub_dpkg with frequency once-per-instance
2025-07-02 17:46:06,003 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_grub_dpkg - wb: [644] 24 bytes
2025-07-02 17:46:06,003 - helpers.py[DEBUG]: Running config-grub_dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_grub_dpkg'>)
2025-07-02 17:46:06,003 - cc_grub_dpkg.py[DEBUG]: grub_dpkg disabled by config grub_dpkg/enabled=False
2025-07-02 17:46:06,003 - handlers.py[DEBUG]: finish: modules-config/config-grub_dpkg: SUCCESS: config-grub_dpkg ran successfully and took 0.000 seconds
2025-07-02 17:46:06,003 - modules.py[DEBUG]: Running module apt_configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2025-07-02 17:46:06,003 - handlers.py[DEBUG]: start: modules-config/config-apt_configure: running config-apt_configure with frequency once-per-instance
2025-07-02 17:46:06,003 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_apt_configure - wb: [644] 24 bytes
2025-07-02 17:46:06,005 - helpers.py[DEBUG]: Running config-apt_configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_apt_configure'>)
2025-07-02 17:46:06,005 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2025-07-02 17:46:06,015 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-07-02 17:46:06,015 - util.py[DEBUG]: Reading 400 bytes from /etc/os-release
2025-07-02 17:46:06,016 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-07-02 17:46:06,016 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-07-02 17:46:06,016 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2025-07-02 17:46:06,016 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:06,054 - performance.py[DEBUG]: Running ['lsb_release', '--all'] took 0.038 seconds
2025-07-02 17:46:06,054 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2025-07-02 17:46:06,056 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2025-07-02 17:46:06,056 - cc_apt_configure.py[DEBUG]: got security mirror: None
2025-07-02 17:46:06,057 - util.py[DEBUG]: search for mirror in candidates: '['http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/', 'http://ap-south-1b.clouds.archive.ubuntu.com/ubuntu/', 'http://ap-south-1.clouds.archive.ubuntu.com/ubuntu/']'
2025-07-02 17:46:06,065 - util.py[DEBUG]: found working mirror: 'http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/'
2025-07-02 17:46:06,065 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-07-02 17:46:06,065 - distros[DEBUG]: filtered distro mirror info: {'primary': 'http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/', 'security': 'http://security.ubuntu.com/ubuntu'}
2025-07-02 17:46:06,065 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'MIRROR': 'http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/'}
2025-07-02 17:46:06,069 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2025-07-02 17:46:06,075 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.deb822.tmpl (quiet=False)
2025-07-02 17:46:06,080 - util.py[DEBUG]: Reading 3091 bytes from /etc/cloud/templates/sources.list.ubuntu.deb822.tmpl
2025-07-02 17:46:06,100 - performance.py[DEBUG]: Rendering jinja2 template took 0.020 seconds
2025-07-02 17:46:06,100 - util.py[DEBUG]: Writing to /etc/apt/sources.list.d/ubuntu.sources - wb: [644] 3004 bytes
2025-07-02 17:46:06,101 - util.py[DEBUG]: Reading from /etc/apt/sources.list (quiet=False)
2025-07-02 17:46:06,107 - util.py[DEBUG]: Reading 270 bytes from /etc/apt/sources.list
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_dep11_Components-amd64.yml.gz
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_binary-amd64_Packages to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_binary-amd64_Packages
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_cnf_Commands-amd64 to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_cnf_Commands-amd64
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_dep11_Components-amd64.yml.gz
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_binary-amd64_Packages to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_binary-amd64_Packages
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_cnf_Commands-amd64 to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_cnf_Commands-amd64
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_dep11_Components-amd64.yml.gz
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_InRelease to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_InRelease
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_binary-amd64_Packages to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_binary-amd64_Packages
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_InRelease to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_InRelease
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_i18n_Translation-en to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_i18n_Translation-en
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_binary-amd64_Packages to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_binary-amd64_Packages
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_i18n_Translation-en to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_i18n_Translation-en
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_i18n_Translation-en to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_i18n_Translation-en
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_cnf_Commands-amd64 to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_cnf_Commands-amd64
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_cnf_Commands-amd64 to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_cnf_Commands-amd64
2025-07-02 17:46:06,110 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_i18n_Translation-en to /var/lib/apt/lists/ap-south-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_i18n_Translation-en
2025-07-02 17:46:06,111 - handlers.py[DEBUG]: finish: modules-config/config-apt_configure: SUCCESS: config-apt_configure ran successfully and took 0.107 seconds
2025-07-02 17:46:06,111 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2025-07-02 17:46:06,111 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2025-07-02 17:46:06,112 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_byobu - wb: [644] 23 bytes
2025-07-02 17:46:06,112 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_byobu'>)
2025-07-02 17:46:06,112 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2025-07-02 17:46:06,112 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully and took 0.000 seconds
2025-07-02 17:46:06,112 - main.py[DEBUG]: Ran 5 modules with 0 failures
2025-07-02 17:46:06,112 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-02 17:46:06,112 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-07-02 17:46:06,113 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp0a2z4g45) - w: [644] 502 bytes/chars
2025-07-02 17:46:06,113 - performance.py[DEBUG]: cloud-init stage: 'modules-config' took 0.326 seconds
2025-07-02 17:46:06,113 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-07-02 17:46:11,008 - log_util.py[DEBUG]: Cloud-init v. 25.1.2-0ubuntu0~24.04.1 running 'modules:final' at Wed, 02 Jul 2025 17:46:10 +0000. Up 19.02 seconds.
2025-07-02 17:46:11,008 - main.py[INFO]: PID [1] started cloud-init 'modules:final'.
2025-07-02 17:46:11,047 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-07-02 17:46:11,049 - modules.py[INFO]: Skipping modules 'package_update_upgrade_install,fan,landscape,lxd,ubuntu_drivers,write_files_deferred,puppet,chef,ansible,mcollective,salt_minion,phone_home,power_state_change' because no applicable config is provided.
2025-07-02 17:46:11,050 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2025-07-02 17:46:11,050 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2025-07-02 17:46:11,052 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_reset_rmc - wb: [644] 25 bytes
2025-07-02 17:46:11,052 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_reset_rmc'>)
2025-07-02 17:46:11,053 - cc_reset_rmc.py[DEBUG]: module disabled, RSCT_PATH not present
2025-07-02 17:46:11,053 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully and took 0.003 seconds
2025-07-02 17:46:11,053 - modules.py[DEBUG]: Running module scripts_vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2025-07-02 17:46:11,053 - handlers.py[DEBUG]: start: modules-final/config-scripts_vendor: running config-scripts_vendor with frequency once-per-instance
2025-07-02 17:46:11,053 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_vendor - wb: [644] 25 bytes
2025-07-02 17:46:11,053 - helpers.py[DEBUG]: Running config-scripts_vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_vendor'>)
2025-07-02 17:46:11,053 - handlers.py[DEBUG]: finish: modules-final/config-scripts_vendor: SUCCESS: config-scripts_vendor ran successfully and took 0.000 seconds
2025-07-02 17:46:11,054 - modules.py[DEBUG]: Running module scripts_per_once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2025-07-02 17:46:11,054 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_once: running config-scripts_per_once with frequency once
2025-07-02 17:46:11,054 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 24 bytes
2025-07-02 17:46:11,054 - helpers.py[DEBUG]: Running config-scripts_per_once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2025-07-02 17:46:11,054 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_once: SUCCESS: config-scripts_per_once ran successfully and took 0.000 seconds
2025-07-02 17:46:11,054 - modules.py[DEBUG]: Running module scripts_per_boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2025-07-02 17:46:11,055 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_boot: running config-scripts_per_boot with frequency always
2025-07-02 17:46:11,055 - helpers.py[DEBUG]: Running config-scripts_per_boot using lock (<cloudinit.helpers.DummyLock object at 0x74440a0b3b90>)
2025-07-02 17:46:11,057 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_boot: SUCCESS: config-scripts_per_boot ran successfully and took 0.002 seconds
2025-07-02 17:46:11,057 - modules.py[DEBUG]: Running module scripts_per_instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2025-07-02 17:46:11,057 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_instance: running config-scripts_per_instance with frequency once-per-instance
2025-07-02 17:46:11,057 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_per_instance - wb: [644] 25 bytes
2025-07-02 17:46:11,058 - helpers.py[DEBUG]: Running config-scripts_per_instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_per_instance'>)
2025-07-02 17:46:11,059 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_instance: SUCCESS: config-scripts_per_instance ran successfully and took 0.000 seconds
2025-07-02 17:46:11,059 - modules.py[DEBUG]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2025-07-02 17:46:11,059 - handlers.py[DEBUG]: start: modules-final/config-scripts_user: running config-scripts_user with frequency once-per-instance
2025-07-02 17:46:11,059 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_user - wb: [644] 24 bytes
2025-07-02 17:46:11,060 - helpers.py[DEBUG]: Running config-scripts_user using lock (<FileLock using file '/var/lib/cloud/instances/i-0dea03404379d6b00/sem/config_scripts_user'>)
2025-07-02 17:46:11,060 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=False, capture=False)
